### ISSUE TITLE
PatInv : Error in "from use.use import UseSimilarity"

### ISSUE THREAD

**Issue by saurabh9329** [RobustNLP/TestTranslation#1]
In PatInv code
I tried installing "use" using pip but it doesnt contain any module as use.use. 
Getting an error -"No module named 'use.use'"
Kindly help

**Comment by PinjiaHe** [comment]
Please kindly refer to our reply at: https://github.com/RobustNLP/TestTranslation/issues/2#issuecomment-771933569
