### ISSUE TITLE
PatInv: Line no 484 install_USE.sh and install Universal sentence encoder before running the code below 

### ISSUE THREAD

**Issue by saurabh9329** [RobustNLP/TestTranslation#2]
where to find install_USE.sh to install Universal sentence encoder

**Comment by PinjiaHe** [comment]
Thanks for reporting this! We have fixed this by adding back the UseSimilarity class

https://github.com/RobustNLP/TestTranslation/blob/8e0d7f426fa4d6d087d988da7a93df9644fb894e/code/PatInv/PatInv.py#L29

Please kindly take a look to see whether it works now.
